@startuml

class "Main" {
    + executar_comandos()
}

class "ReconhecedorDeFala" {
    + ouvir_comando()
    + processar_audio()
}

class "ControladorSpotify" {
    + tocar_musica()
    + pausar()
    + selecionar_dispositivo()
}

class "EnviadorWhatsApp" {
    + enviar_mensagem(numero, mensagem)
}

Main --> ReconhecedorDeFala : "Usa"
Main --> ControladorSpotify : "Controla"
Main --> EnviadorWhatsApp : "Comunica-se"

@enduml
