name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps -r requirements.txt

    - name: Run pylint
      run: |
        pip install pylint
        PYTHONPATH=$PYTHONPATH:. pylint .

    - name: Gerar Diagrama UML
      run: |
        plantuml -tsvg -o diagrams/ marvin_diagram.puml

    - name: Upload Diagrama UML
      uses: actions/upload-artifact@v3
      with:
        name: uml-diagram
        path: diagrams/

