name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Set up JDK 11 (for SonarCloud)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Verify Java Version (JDK 11)
      run: java -version

    - name: Install SonarScanner (specific version)
      run: |
        # Baixar e instalar uma versão compatível do SonarScanner
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
        unzip sonar-scanner-cli-4.8.0.2856-linux.zip
        export SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.8.0.2856-linux
        echo "SonarScanner installed successfully"

    - name: Set PATH for SonarScanner
      run: |
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        sonar-scanner --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps -r requirements.txt

    - name: Run pylint
      run: |
        pip install pylint
        PYTHONPATH=$PYTHONPATH:. pylint .

    - name: Run tests
      run: |
        pytest

    - name: Run SonarScanner
      run: |
        export PATH=$SONAR_SCANNER_HOME/bin:$PATH
        sonar-scanner \
          -Dsonar.projectKey=josevilanir_Marvin \
          -Dsonar.organization=josevilanir \
          -Dsonar.python.version=3.11
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
