name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps -r requirements.txt  # Adicionando --no-deps para evitar instalar dependências

    - name: Run pylint
      run: |
        pip install pylint
        PYTHONPATH=$PYTHONPATH:. pylint MARVIN/ --exit-zero

    - name: Run tests
      run: |
        pytest

    - name: Lint code
      run: |
        pip install flake8
        flake8 .

    - name: Validate README.md
      run: |
        python check_readme.py
