name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-deps -r requirements.txt

    - name: Run pylint
      run: |
        pip install pylint
        PYTHONPATH=$PYTHONPATH:. pylint .

    #- name: Run tests
      #run: |
      #  pytest
    
    - name: Verificar Conformidade de Camadas
      run: python-layer-linter --config layers.yaml
